#docker compose
version: '3'
services:
    revanced-builder:
        container_name: revanced-builder
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        image: vo1dbin/revanced:3.4.15
        depends_on:
            - pyhttp
        volumes:
            - ./revanced/:/app/revanced-builder/revanced/
        ports:
            - 8888:8000
